### ISSUE TITLE
Whitespace is ignored

### ISSUE THREAD

**Issue by denis-sokolov** [rayd/html-parse-stringify2#10]
Empty text nodes are [explicitly discarded](https://github.com/rayd/html-parse-stringify2/blob/498a62caea5a863c4a276b9844bc0bafbd07bdb4/lib/parse.js#L12). However, that is clearly wrong in some cases. Perhaps we should only collapse whitespace, but not discard it?

```html
Before parsing:
<p><span>Hello,</span> <span>world!</span></p>
After parsing:
<p><span>Hello,</span><span>world!</span></p>
```

#9 provides an opt-in solution, but perhaps this should not be opt-in?

**Comment by rayd** [comment]
This should be resolved by #9 and this commit: 99d99ec68861503ed8781e70ebc783809c26f5da. The default now is for us to collapse whitespace, not ignore it. Since this was a potentially breaking change, I've updated the major version number to 2.
